version: '3.8'
services:
  web:
    container_name: form-to-pdf-web
    build:
      context: .
      target: form-to-pdf-web
    environment:
      TZ: "America/Los_Angeles"
    networks:
      - reverse
  server:
    container_name: form-to-pdf-server
    build:
      context: .
      target: form-to-pdf-server
    environment:
      TZ: "America/Los_Angeles"
    networks:
      - reverse
networks:
  reverse:
    name: reverse_default
